//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach_Luzin_Patrakov_321
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KursachEntities : DbContext
    {
        public KursachEntities()
            : base("name=KursachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    /*
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<ContactInfo> ContactInfo { get; set; }
        public virtual DbSet<Cosplayers> Cosplayers { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<InvitedUsers> InvitedUsers { get; set; }
        public virtual DbSet<LocationInfo> LocationInfo { get; set; }
        public virtual DbSet<LocationParticipants> LocationParticipants { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Organizers> Organizers { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<PurchasedItems> PurchasedItems { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<TicketInfo> TicketInfo { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<TicketTypes> TicketTypes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    */
    }
}
