//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach_Luzin_Patrakov_321
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stalls
    {
        public int StallID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string StallName { get; set; }
        public string Description { get; set; }
    
        public virtual Locations Locations { get; set; }
        public virtual Vendors Vendors { get; set; }
    }
}
