//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach_Luzin_Patrakov_321
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketInfo
    {
        public int TicketInfoID { get; set; }
        public Nullable<int> TicketID { get; set; }
        public string TicketInfo1 { get; set; }
    
        public virtual Tickets Tickets { get; set; }
    }
}
