//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach_Luzin_Patrakov_321
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendors()
        {
            this.Stalls = new HashSet<Stalls>();
        }
    
        public int VendorID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> ContactInfoID { get; set; }
    
        public virtual ContactInfo ContactInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stalls> Stalls { get; set; }
        public virtual Users Users { get; set; }
    }
}
